author: M. Grady Saunders
source: .
title: mgradysaunders.github.io
logo: ./images/profile.png
description: C++17 header-only utilities
destination: ./_site
encoding: "utf-8"
markdown: kramdown
markdown_ext: "markdown,md"
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
liquid:
  error_mode: strict
